/*
 * Collection Service
 * API for managing collection
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ProductlistProductListEntity;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProductlistGetProductListByUrlKeyResponse
 */
public class ProductlistGetProductListByUrlKeyResponseTest {
    private final ProductlistGetProductListByUrlKeyResponse model = new ProductlistGetProductListByUrlKeyResponse();

    /**
     * Model tests for ProductlistGetProductListByUrlKeyResponse
     */
    @Test
    public void testProductlistGetProductListByUrlKeyResponse() {
        // TODO: test ProductlistGetProductListByUrlKeyResponse
    }

    /**
     * Test the property '_list'
     */
    @Test
    public void _listTest() {
        // TODO: test _list
    }

}
