/*
 * Collection Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.SetProductListAssociationsRequestAssociation;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProductlistSetProductListAssociationsRequest
 */
public class ProductlistSetProductListAssociationsRequestTest {
    private final ProductlistSetProductListAssociationsRequest model = new ProductlistSetProductListAssociationsRequest();

    /**
     * Model tests for ProductlistSetProductListAssociationsRequest
     */
    @Test
    public void testProductlistSetProductListAssociationsRequest() {
        // TODO: test ProductlistSetProductListAssociationsRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'listId'
     */
    @Test
    public void listIdTest() {
        // TODO: test listId
    }

    /**
     * Test the property 'productGrn'
     */
    @Test
    public void productGrnTest() {
        // TODO: test productGrn
    }

    /**
     * Test the property 'associations'
     */
    @Test
    public void associationsTest() {
        // TODO: test associations
    }

}
