/*
 * Collection Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ProductlistBulkUpdateProductListAssociationsRequestProductListAssociation;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProductlistBulkUpdateProductListAssociationsRequest
 */
public class ProductlistBulkUpdateProductListAssociationsRequestTest {
    private final ProductlistBulkUpdateProductListAssociationsRequest model = new ProductlistBulkUpdateProductListAssociationsRequest();

    /**
     * Model tests for ProductlistBulkUpdateProductListAssociationsRequest
     */
    @Test
    public void testProductlistBulkUpdateProductListAssociationsRequest() {
        // TODO: test ProductlistBulkUpdateProductListAssociationsRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'productListAssociations'
     */
    @Test
    public void productListAssociationsTest() {
        // TODO: test productListAssociations
    }

}
