/*
 * Collection Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ProductlistProductListAssociation;
import org.openapitools.client.model.ProductlistProductListAssociationError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProductlistDeleteProductListAssociationResponse
 */
public class ProductlistDeleteProductListAssociationResponseTest {
    private final ProductlistDeleteProductListAssociationResponse model = new ProductlistDeleteProductListAssociationResponse();

    /**
     * Model tests for ProductlistDeleteProductListAssociationResponse
     */
    @Test
    public void testProductlistDeleteProductListAssociationResponse() {
        // TODO: test ProductlistDeleteProductListAssociationResponse
    }

    /**
     * Test the property 'association'
     */
    @Test
    public void associationTest() {
        // TODO: test association
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

}
