/*
 * Collection Service
 * API for managing collection
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ProductlistProductListAssociation;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProductlistListProductListAssociationsResponse
 */
public class ProductlistListProductListAssociationsResponseTest {
    private final ProductlistListProductListAssociationsResponse model = new ProductlistListProductListAssociationsResponse();

    /**
     * Model tests for ProductlistListProductListAssociationsResponse
     */
    @Test
    public void testProductlistListProductListAssociationsResponse() {
        // TODO: test ProductlistListProductListAssociationsResponse
    }

    /**
     * Test the property 'associations'
     */
    @Test
    public void associationsTest() {
        // TODO: test associations
    }

    /**
     * Test the property 'nextPageToken'
     */
    @Test
    public void nextPageTokenTest() {
        // TODO: test nextPageToken
    }

}
