/*
 * Collection Service
 * API for managing collection
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProductlistBulkUpdateProductListAssociationsRequestProductListAssociation
 */
public class ProductlistBulkUpdateProductListAssociationsRequestProductListAssociationTest {
    private final ProductlistBulkUpdateProductListAssociationsRequestProductListAssociation model = new ProductlistBulkUpdateProductListAssociationsRequestProductListAssociation();

    /**
     * Model tests for ProductlistBulkUpdateProductListAssociationsRequestProductListAssociation
     */
    @Test
    public void testProductlistBulkUpdateProductListAssociationsRequestProductListAssociation() {
        // TODO: test ProductlistBulkUpdateProductListAssociationsRequestProductListAssociation
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'position'
     */
    @Test
    public void positionTest() {
        // TODO: test position
    }

}
