/*
 * Collection Service
 * API for managing collection
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ProductlistProductListEntity;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProductlistSearchProductListsResponse
 */
public class ProductlistSearchProductListsResponseTest {
    private final ProductlistSearchProductListsResponse model = new ProductlistSearchProductListsResponse();

    /**
     * Model tests for ProductlistSearchProductListsResponse
     */
    @Test
    public void testProductlistSearchProductListsResponse() {
        // TODO: test ProductlistSearchProductListsResponse
    }

    /**
     * Test the property 'results'
     */
    @Test
    public void resultsTest() {
        // TODO: test results
    }

    /**
     * Test the property 'totalSize'
     */
    @Test
    public void totalSizeTest() {
        // TODO: test totalSize
    }

}
