/*
 * Collection Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SetProductListAssociationsRequestAssociation
 */
public class SetProductListAssociationsRequestAssociationTest {
    private final SetProductListAssociationsRequestAssociation model = new SetProductListAssociationsRequestAssociation();

    /**
     * Model tests for SetProductListAssociationsRequestAssociation
     */
    @Test
    public void testSetProductListAssociationsRequestAssociation() {
        // TODO: test SetProductListAssociationsRequestAssociation
    }

    /**
     * Test the property 'listId'
     */
    @Test
    public void listIdTest() {
        // TODO: test listId
    }

    /**
     * Test the property 'position'
     */
    @Test
    public void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'productGrn'
     */
    @Test
    public void productGrnTest() {
        // TODO: test productGrn
    }

}
